spring:
  application:
    name: application-service

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:application_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

server:
  port: 8083

app:
  upload-dir: ${RESUME_UPLOAD_DIR:uploads/resumes}

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    hostname: localhost
    instance-id: ${spring.application.name}:${server.port}

logging:
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info

  endpoint:
    health:
      show-details: always

security:
  jwt:
    secret: ${JWT_SECRET}

springdoc:
  api-docs:
    path: /v3/api-docs

  swagger-ui:
    path: /swagger-ui.html