CREATE DATABASE IF NOT EXISTS profile_db;
USE profile_db;
CREATE TABLE IF NOT EXISTS profiles (
 id BIGINT AUTO_INCREMENT PRIMARY KEY, user_id BIGINT NOT NULL UNIQUE, role VARCHAR(30) NOT NULL, full_name VARCHAR(255) NOT NULL,
 email VARCHAR(255), phone VARCHAR(255), location VARCHAR(255), bio TEXT, skills TEXT, company VARCHAR(500), resume_url VARCHAR(500),
 created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
